### ISSUE TITLE
channelIdで65535以上の数を利用する際にambientサーバにconnect出来ない場合がある

### ISSUE THREAD

**Issue by isp-t-shimizu** [AmbientDataInc/Ambient_ESP8266_lib#3]
- 現象
    - 私の利用の環境(Arduino/ATMega2560 R3+ ESP-12S)で利用した際に、データをambientサーバに登録できない現象がありました。
- 詳細
    - デバッグしてみたところ、channelIdが65535を超えている際に、loopしたchannelIdでサーバに登録しているように見えました。(例えば67535をchannelIdとして利用しようとすると、2000で登録しに行こうとしているようにlogでは見える)
- 対応
    - 上記現象から、(処理系によるのだとは思いますが)unsigned short的に扱われているようだと推測し、channelIdを利用している箇所をすべて、unsigned long channelIdとしたり、%uで出力させているところを%luとすることで、登録できるようになりましたのでご報告です。

**Comment by TakehikoShimojima** [comment]
AmbientのArduinoライブラリはESP8266/ESP32（ともに32ビットCPU）用のライブラリで、それ以外のアーキテクチャはサポートしていません。

Arduino/ATMega2560では、intが16ビットで扱われるため、16ビット（65535）を超える値が扱えない（ループする）ため、ご指摘のような現象になるものと思われます。Ambientでは8ビットアーキテクチャのCPUをサポートする予定はありませんので、ご自分でライブラリを修正してご対応ください。

**Comment by isp-t-shimizu** [comment]
ご回答ありがとうございます。
なるほど、サポート外であったとのこと失礼いたしました。内容承知いたしました。
私の環境では修正して動作いたしましたので、もし8bit環境で利用される方がいればご参考ください。
